// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTBdigkjSiMWcTnesZ-YY2ul3tsmZfWQ',
    appId: '1:504428186365:web:aa3e67c7712378e2934c94',
    messagingSenderId: '504428186365',
    projectId: 'my-aid-trial',
    authDomain: 'my-aid-trial.firebaseapp.com',
    storageBucket: 'my-aid-trial.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB68nfjLjkIVHnS4InVCgYIzblL_qwkAK4',
    appId: '1:504428186365:android:a6ba7467053063e5934c94',
    messagingSenderId: '504428186365',
    projectId: 'my-aid-trial',
    storageBucket: 'my-aid-trial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMEIesX1uxn4p7jNMhNg0xapS3lHgrQA',
    appId: '1:504428186365:ios:5703a68ee2e7677a934c94',
    messagingSenderId: '504428186365',
    projectId: 'my-aid-trial',
    storageBucket: 'my-aid-trial.appspot.com',
    iosBundleId: 'com.example.myAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQMEIesX1uxn4p7jNMhNg0xapS3lHgrQA',
    appId: '1:504428186365:ios:05ed73c55b4da987934c94',
    messagingSenderId: '504428186365',
    projectId: 'my-aid-trial',
    storageBucket: 'my-aid-trial.appspot.com',
    iosBundleId: 'com.example.myAid.RunnerTests',
  );
}
