// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eQrsLjkr5nZBCOIz7pq4DpYxH6ynMrg',
    appId: '1:440320041360:web:ed073fa694618c57035315',
    messagingSenderId: '440320041360',
    projectId: 'myaid-818d5',
    authDomain: 'myaid-818d5.firebaseapp.com',
    storageBucket: 'myaid-818d5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9FflkR0QU_TYN9zgKmj07yo6SA0sjEt8',
    appId: '1:440320041360:android:450be009c734a6aa035315',
    messagingSenderId: '440320041360',
    projectId: 'myaid-818d5',
    storageBucket: 'myaid-818d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ZpI-ty2cC0VOA4EWrYGJMCMFj1MHgiE',
    appId: '1:440320041360:ios:8d5dadf6cdfbdf92035315',
    messagingSenderId: '440320041360',
    projectId: 'myaid-818d5',
    storageBucket: 'myaid-818d5.appspot.com',
    iosClientId: '440320041360-tovp4pvbtjs6ib0h4ulthsd4aa5vb865.apps.googleusercontent.com',
    iosBundleId: 'com.aid.app.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ZpI-ty2cC0VOA4EWrYGJMCMFj1MHgiE',
    appId: '1:440320041360:ios:408bf72acbb9c99f035315',
    messagingSenderId: '440320041360',
    projectId: 'myaid-818d5',
    storageBucket: 'myaid-818d5.appspot.com',
    iosClientId: '440320041360-civ583vf2bvgs2ke1vhf1ii0ipbr5k7g.apps.googleusercontent.com',
    iosBundleId: 'com.aid.aid1.RunnerTests',
  );
}
